### ISSUE TITLE
Request blocked by CORS policy

### ISSUE THREAD

**Issue by bernard-ng** [Divlo/FunctionProject#1]
when trying to use **Conversion des Encodages de caractères**, I've got the following error in the console,(  I took a while to get the response so checked what was going wrong )

Access to XMLHttpRequest at 'https://api.function.divlo.fr/functions/convertEncoding' from origin 'https://function.divlo.fr' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by theoludwig** [comment]
No problem for me. If you install it locally you would have no problem.
But I know that sometime my server went down for a couple of minutes and then go back again. That's why sometime it's not working, I have no idea why it's happening.
Thanks for the information.
