### ISSUE TITLE
Mini url en attente

### ISSUE THREAD

**Issue by NicoWithManyO** [Divlo/FunctionProject#15]
### Question
Hello ! Toujours fan du service ;) J'aimerai avoir la possibilité de "mettre en pause" une url.
(exemple : en fin de saison 17, le lien reglement doit etre mis en pause, avant que le reglementS18 soit disponible. je pourrais supprimer le lien, mais ca serait mieux de pouvoir "active/desactive" non ? 
Soit ca afficherais une page perso qui dirait que l'url n'est actuellement pas utilisée, soit l'erreur comme si le raccourci n'existait pas ?
J'ai essayé de laisser le champ vide, mais ca ne passe pas ...

Merci ;)

**Comment by theoludwig** [comment]
Salut @NicoWithManyO! 👋

Merci pour tes retours, c'est toujours cool d'avoir des utilisateurs actifs et qui propose des façons d'améliorer le projet!
Concernant ton idée, si je comprends, t'aimerais bien désactiver un lien puis le réactiver plus tard, donc par exemple, tu aimerais désactiver le lien du réglement de la saison 17, comme ça les personnes qui vont sur le lien raccourci, ne peuvent plus y accéder, par contre sur ton "dashboard" tu peux toujours le voir, le modifier et le réactiver du coup, c'est bien ça ?
Oui je ne pense pas que sa soit très compliqué à implémenter, c'est seulement un booléen à rajouter.

**Comment by NicoWithManyO** [comment]
Oui c ça car à chaque saison je ne change que l'URL cible de la redirection
(le le raccourci est le même de saison en saison)

**Comment by theoludwig** [comment]
Le projet n'est plus maintenu et ne prévoit pas de futures améliorations pour l'instant.
Merci encore pour ta contribution @NicoWithManyO et le projet reste tout de même accessible! :smile:
