### ISSUE TITLE
Modification de l'url cible

### ISSUE THREAD

**Issue by NicoWithManyO** [Divlo/FunctionProject#4]
Hi ! Un grand merci pour se service !
Serait il envisageable (par un système d'authentification éventuellement) que l'url cible soit modifiable à souhait une fois le raccourci créé ?
Peut être aussi (comme discuté) qu'il serait possible de raccourcir le sous-domaine ("short-link.divlo" en "short.divlo" ...) ?
Je suis en tous les cas, en l'état, ravi de ce service !

**Comment by theoludwig** [comment]
Salut, 

Merci pour ton retour, effectivement, c'est des bonnes idées, je tiens ça en compte, mais ce n'est pas ma priorité actuellement.
SI j'arrive à avoir un peu de temps pour améliorer ça, voilà un potentiel résumé des changements : 

- Mettre open-source le code pour https://short-links.divlo.fr/ sur ce repo (+ réimplémentation en Node.js avec express.js, pour le moment écrit en PHP).
- Changer l'URL pour que ça soit `short.divlo.fr`
- Enlever le `?q` à la fin de l'URL, mais directement le nom du raccourci (plus le lien est court, mieux c'est).
- Un système où les utilisateurs inscrit sur le site pourrait voir les liens précédemment raccourci et changer leur noms si disponible.

**Comment by NicoWithManyO** [comment]
Hi je te réponds ici, mais bien-sur OP pour en discuter sur discord si
besoin ;)

   - Un système où les utilisateurs inscrit sur le site pourrait voir les
   liens précédemment raccourci et changer leur noms si disponible

je ne suis pas sur que l'on se soit compris, moi ce dont je parlais était
plutôt le contraire :
ne pas changer le nom du raccourci, mais plutôt l'url vers lequel il renvoi
... le même raccourci pourrait d'abord envoyer vers google.fr puis je
modifie pour qu'il envoie vers divlo.fr :)

Bonne soirée à toi ;)

**Comment by theoludwig** [comment]
Je préfère qu'on en parle ici car c'est plus approprié! 😄
Effectivement je n'avais pas compris, sinon ce que je peux faire c'est laisser la possibilité de modifier les deux si possible ?
L'URL ou le nom du raccourci, qu'est ce que t'en penses ? @NicoWithManyO 
D'ailleurs si tu aimes le projet, tu peux mettre une étoile sur GitHub (un peu comme une sorte de like), merci.

**Comment by NicoWithManyO** [comment]
ha oui clairement, ça peut éviter que du coup on en créer des nouveaux
inutilement ?
et puis en cas d'erreur ... parfait !

super !
