### ISSUE TITLE
Compteur de cliques

### ISSUE THREAD

**Issue by NicoWithManyO** [Divlo/FunctionProject#7]
Me revoilà,
tu réponds tellement bien à mes requêtes, que j'en ai une autre ;)
Un éventuel compteur de cliques, simple et pas forcément précis, juste afin d'avoir une petite idée ...

Encore merci pour ce service, qui va simplifier la vie de toutes notre organisation !

NicoOoOoOoo pour E-magine Gaming !

**Comment by theoludwig** [comment]
Yep bonne idée, c'est ajouté!
